#!/bin/bash
# This is the script that i3 runs to either start tmux in
# the dropdown terminal or log into a previous session.
echo 'spawning tmux' >> ~/.xsession-errors
tmux a || tmux
echo 'finished spawning tmux' >> ~/.xsession-errors
