#!/usr/bin/env bash

###################
# Simple script to translate what's selected on your linux machine
# Author: Vik Ramanujam (Github: @vviikk)
# Dependencies:
#  https://github.com/soimort/translate-shell
#  xdotool, xsel
#  
# Instructions: Download this file, chmod +x it, sudo move it to /usr/bin
#               and use your desktop environment to bind it to a keybinding
#               For example, I use Supet + T to fire `translate -a` when I'm
#               typing something into an input box (chat, whatsapp...)
#               and the text I have typed is translated to Spanish.
#               And I use Super+Shift+T to fire `translate -n` to display
#               a translation as a notification
##################
while getopts na FLAG
do
    case "${FLAG}" in
        n) NOTIFY="TRUE";;
        a) SELECT_ALL="TRUE";;
    esac
done


if [[ $SELECT_ALL ]]
then
  echo "selecting all text"
  xdotool key --clearmodifiers "ctrl+a"
fi

SELECTION=$(xsel -o)
RESULT=$( echo $SELECTION | trans -b -t es)

if [[ $NOTIFY ]]
then
  notify-send --icon=info "$SELECTION" "$RESULT"
fi

echo $RESULT | xclip -selection clipboard
xdotool key --clearmodifiers "ctrl+v"

# vim: ft=sh: set et ts=4 sw=4 sts=4:
