directory: ~/Music
library: ~/Music/beet/musiclibrary.db

threaded: yes

import:
  move: yes
  quiet_fallback: skip

plugins: [
  info,
  beatport,
  # fetchart,
  embedart,
  ftintitle,
  lastgenre,
  missing,
  chroma,
  scrub,
  # zero,
  # plexupdate,
  duplicates,
  discogs,
  mbcollection,
  convert,
  permissions
]

# Plugin settings
acousticbrainz:
  force: yes

ftintitle:
  auto: yes
  format: (feat. {0})

chroma:
  auto: yes

musicbrainz:
  user: piggyslasher
  pass: 

mbcollection:
  auto: no

duplicates:
  count: yes
  tag: dup=1

ignore: .AppleDouble ._* *~ .DS_Store

# Paths ----------------------------------------------------------------------

# Paths and filenames for music files
# relative to music directory
paths:
  default: $albumartist/$artist - $title
